# 静态资源路径
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: # 页面表单的问题
#    static-path-pattern: /hahhh/**
#  web:
#    resources:
#      static-locations: classpath:/res/
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
