### 测试应用根页面
GET / HTTP/1.1
Host: {{host}} 

###
GET /hello HTTP/1.1
Host: {{host}}

### 测试
GET /servlet/user HTTP/1.1
Host: {{host}} 

###
GET /servlet/hello?name=foo你 HTTP/1.1
Host: {{host}} 

### JerryMouse
GET / HTTP/1.1
Host: {{host}} 
