
### 测试参数接收
GET /mvc/user HTTP/1.1
Host: {{host}}

POST /mvc/user/insert HTTP/1.1
Host: {{host}}

{
    "name": "foo",
    "age": 12,
    "address": {
        "country": "cn",
        "city": "beijing"
    }
}